import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ClipboardContextProvider } from "./api/context/ClipboardContext";
import { Navbar } from "./_components/navbar";
import clsx from "clsx";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TRPCReactProvider>
        <ClipboardContextProvider>
          <body
            className={clsx(
              "flex h-[100svh] flex-col bg-black font-sans text-white",
              inter.variable,
            )}
          >
            {children}
          </body>
        </ClipboardContextProvider>
      </TRPCReactProvider>
    </html>
  );
}
