import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ClipboardContextProvider } from "./api/context/ClipboardContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${inter.variable}
          flex h-[100svh] items-center justify-center bg-black p-4 font-sans text-white
        `}
      >
        <TRPCReactProvider>
          <ClipboardContextProvider>{children}</ClipboardContextProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
